### PR TITLE
Added tests for dd_to_dms

### PR DESCRIPTION
**Pull request by HawardKetoyoMsatsi**
@dannyparsons @lilyclements I added test-dd_to_dms.R function which runs automatic tests to test whether :
1. the output is of the desired length,
2. the output is correct given an integer input,
3. the output is correct given a negative decimal,
4. the output is correct given a positive decimal input.

### CODE REVIEW

**Review by dannyparsons — APPROVED** [review]
This looks great, well done! This is exactly the kind of thing that's needed.

For a future improvement, I would probably suggest using a slightly more varied set of numbers i.e. not have the positive and negative numbers the same in value e.g. 3.3 and -56,8, just to have a bit more variation and chance of detecting issues.

No need to change that here, just keep in mind for future.

Also, I see the PR is from your `main` branch. It would be better to create a new branch for each PR so that your `main` remains clean to be updated regularly. As we do for R-Instat.

**Comment by dannyparsons** [comment]
Note that the tests have run and are all passing.

**Comment by dannyparsons** [comment]
@HawardKetoyoMsatsi Please continue now with tests for the `climatic_summary` function. Thanks.

**Comment by HawardKetoyoMsatsi** [comment]
Noted with thanks. @dannyparsons could you please confirm that you didn't swap Lattitude with longitude conditions. I had a feeling that they might have been swapped. 
I will be moving to `climatic_summary` later in the day once am done opening a PR on an issue I am working on in R-Instat.

**Pull request merged**
